src/serialbox-fortran/m_serialize.f90

This shall be a solution for #12.
I added an optional variable to fs_create_serializer for the archive type, so it should be backward compatible.

NetCDF support in Fortran interface

---

src/serialbox-fortran/utils_ppser.f90

This item was missing after @chovyy 's fix. I named the parameter the same as in the called function, `opt_archive` which might not be the best name, because most parameters passed by pp_ser.py are optional. 
(This is my first ever public PR in Fortran ;-) ).

Adds support for opt_archive parameter in pp_ser.py Python preprocessor

---

src/serialbox-fortran/m_serialize.f90
test/serialbox-fortran/serialbox_test.pf

Read/write routines for LOGICALs were missing in the Fortran interface. This pull request fixes this.
Since `LOGICAL` and `LOGICAL(KIND=C_BOOL)` is usually not the same in Fortran, I have added a set of routines for both types, but those for LOGICALs with default kind only delegate to the others.
I have also extended the unit tests with test cases for LOGICALs.

[Fortran] Added read/write routines for LOGICAL and LOGICAL(KIND=C_BOOL)

---

CMakeLists.txt

I'm always confused when I read `serialbox` in the project explorer.
Old: 
New:

Rename project to serialbox2

---

src/serialbox/core/Exception.h
src/serialbox/core/frontend/stella/Savepoint.cpp
src/serialbox/core/frontend/stella/SerializationException.h
src/serialbox/core/frontend/stella/Serializer.h

The serializer #includes the needed headers from STELLA and
defines the correct API for writing and reading into/from a
STELLA data field. The information about the storage directions
and the strides is inferred from the field itself. The interface
to initialize a field has been removed.
The #include to the Serialbox `Exception.h` header has been remove to
prevent the exposure of C++11 code. The `SERIALBOX_NOEXCEPT` macro
is defined again here.

Adapt Serializer and SerializationException for STELLA

---

cmake/SerialboxConfig.cmake.in

You get something less confusing, because it does not end with "../". Just a proposal.

Use get_filename_componet to get real path of serialbox

---

src/serialbox-python/pp_ser/pp_ser.py

"-o/--output" option allows to preprocess a single file and provide the output filename.

Added output option to process (and rename) single file

---

src/serialbox-python/pp_ser/pp_ser.py

The recursive option '-r' will process all '.f90', '.inc' and '.incf' (case insensitive) files in directories given as argument and build the same directory tree in output-dir with the preprocessed files.

Add recursive option

---

src/serialbox/core/Filesystem.h

Bugfix: replace `_GLIBCXX_THROW_OR_ABORT` by `throw` for portability.

Bugfix _GLIBCXX_THROW_OR_ABORT not portable

---

src/serialbox-python/compare/compare.py

Small change that fixes [those NaN != NaN errors](https://github.com/eth-cscs/serialbox2/issues/148).
Since everybody agreed that two NaN values shall pass as equal and I can't see a use case for the (current) opposite behavior, I haven't added a command line option as suggest by @havogt, but if you insist, I can do so.

[compare.py] Both values NaN will no longer raise an error

---

src/serialbox-fortran/m_ser_ftg.f90
test/serialbox-fortran/ser_ftg_test.pf

The FTG functions `ftg_allocate_and_read_*` now reallocate already allocated pointers and allocatables when current shapes do not match to stored sizes.
Should also help with never initialised pointers for which `ASSOCIATED()` arbitrarily returns true.

[FTG] Reallocate

---

src/serialbox-python/compare/compare.py

Format error in scientific notation in compare.py

---

src/serialbox-fortran/m_ser_ftg.f90

I have changed the logic of allocation in the FTG interface.
In `ftg_allocate_pointer_*` variables are now always nullified and then allocated. `ftg_allocate_and_read_pointer_*`now always just calls `ftg_allocate_pointer_*`. Before, it first checked if the pointer variable was already associated and if so if the size matches etc. This still led to seg faults from time to time when undefined pointers were passed.
For consistency, I have also changed `ftg_allocate_allocatable_*` and `ftg_allocate_and_read_allocatable_*` in a similiar way.
I think, the new behavior that the subroutines called `ftg_allocate_*` always (re)allocate is perfectly fine.

[FTG] Fix segfault due to undefined pointers in ftg_allocate_and_read_pointer_*

---

src/serialbox-fortran/m_ser_ftg_cmp.f90

For scalars, matching values are now printed with OK messages by `ftg_compare`.
NOT URGENT!

[FTG] Minor change in ftg_compare

---

src/serialbox-c/Serializer.cpp
src/serialbox-python/serialbox/core.py
src/serialbox/core/SerializerImpl.cpp

Fixes #194, fixes #151 
Additional changes:
Use the default error handler from python.

C: Don't write json in read mode

---

src/serialbox-c/Serializer.cpp

Currently, when you register a zero-sized array with the Fortran or C interface the zero dimensions are left out in the `dims` meta-info. So, even if you know the actual rank, you don't know which dimension is the zero one. Arrays with dimensions (0,4,2), (4,0,2) and (4,2,0) all become `"dims": [4, 2]`. 
I have made a little change to the make_dims function, so that (0,4,2) becomes `"dims": [0, 4, 2]`, (4,0,2) becomes `"dims": [4, 0, 2]` and (4,2,0) stays `"dims": [4, 2]`. 
That's not perfect, but a small improvement.

[C] Respect zero size dimensions

---

src/serialbox-fortran/m_ser_ftg_cmp.f90

Added a missing `ALLOCATE` of the `delta` variable in the `ftg_cmp_print_deviations_*` subroutines in the `m_ser_ftg_cmp` module. I don't know exactly why this is needed and the `mask` variable in line above doesn't need it, but anyway...
The module was generated from this file: [m_ser_ftg_cmp.f90.cht](https://github.com/chovyy/fortrangenerictor/blob/master/m_ser_ftg_cmp.f90.cht).

[FTG] Bug fix in ftg_cmp_print_deviations_*

---

src/serialbox-fortran/m_ser_ftg.f90
src/serialbox-fortran/m_ser_ftg_cmp.f90
src/serialbox-fortran/m_serialize.f90
test/serialbox-fortran/ser_ftg_cmp_test.pf
test/serialbox-fortran/ser_ftg_test.pf
test/serialbox-fortran/serialbox_test.pf

`CHARACTER`s are converted with `IACHAR` and stored as integer array. Conversion to C strings would be too complicated, I guess.

[Fortran] [FTG] Support for strings in Fortran

---

CMakeLists.txt
cmake/Packaging.cmake
cmake/SerialboxConfig.cmake.in
cmake/SerialboxTooling.cmake
cmake/modules/FindNetCDF.cmake
cmake/modules/SerialboxInstallTargets.cmake
cmake/modules/SerialboxTestScript.cmake
docs/CMakeLists.txt
docs/sphinx/Usage.rst
examples/fortran/perturbation/CMakeLists.txt
examples/fortran/perturbation_netcdf/CMakeLists.txt
examples/fortran/simple/CMakeLists.txt
examples/gridtools/smagorinsky/CMakeLists.txt
src/serialbox-c/CMakeLists.txt
src/serialbox-fortran/CMakeLists.txt
src/serialbox-python/CMakeLists.txt
src/serialbox/core/CMakeLists.txt
test/serialbox-fortran/CMakeLists.txt
test/utility/CMakeLists.txt

This PR allows Serialbox to be used in CMake superbuild projects,
so that one could have code like
```
add_subdirectory( serialbox2 )  # --> will set "Serialbox_DIR" in cache
add_subdirectory( project_using_serialbox )
```
and within `project_using_serialbox` we have
```
find_package( Serialbox )  # --> will use Serialbox_DIR as default hint
```
Most issues were related to use of `${CMAKE_BINARY_DIR}` and `${CMAKE_SOURCE_DIR}` which reflect the top-level CMake project rather than `${PROJECT_BINARY_DIR}` and `${PROJECT_SOURCE_DIR}` which reflect the most recent project.
As a result it could be that certain products are no longer in a previously expected directory now, as I am not able to test everything
---
Moreover in this PR I have created alias targets (if possible) …

Modifications to allow Serialbox to be used in CMake superbuild projects

---

CMakeLists.txt

If users want to have native code, the flag should be passed from the command line to CMake configure (e.g. `cmake -DCMAKE_CXX_FLAGS="-march=native"`).

Remove hard-coded -march=native

---

docs/sphinx/Building.rst
docs/sphinx/Documentation.rst
docs/sphinx/Python.rst
examples/fortran/simple/m_ser.F90
examples/gridtools/smagorinsky/CMakeLists.txt
src/serialbox-fortran/m_ser_ftg.f90
src/serialbox-fortran/m_ser_ftg_cmp.f90
src/serialbox-python/sdb/sdbgui/mainwindow.py
tools/cscs-scripts/submit.kesch.slurm

There were some left-over references to serialbox2 instead of serialbox.

Remove references to serialbox2 everywhere

---

AUTHORS
src/serialbox-python/compare/compare.py

Small PR to add the option -f to be able to filter the fields one wants to check with giving a substr as argument. Only fields including the substings are then checked and not all of them. Allows to also compare one field or some types of fields quickly which speeds up the workflow quite a lot (for me at least).

compare.py: add support for filtering fields

---

src/serialbox-python/serialbox/type.py
test/serialbox-python/serialbox/test_serializer.py

DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
**Testing**: Warning is gone for my case.

Silence Deprecation Warning related to np.bool

---

.github/workflows/CI.yml
AUTHORS
CMakeLists.txt
src/serialbox-python/pyproject.toml
src/serialbox-python/requirements.txt
src/serialbox-python/setup.py

Added `${ORIGIN}` to the build `rpath` for python build
when running the python build with pip 
```
cd src/serialbox-python
pip install .
```
the cmake build target is run, after that the shared libraries are copied from the build folder to `site_packages` folder of the python environment. Adding ` ${ORIGIN}` to the `rpath` allows `cdll.LoadLibrary`  to find dependent libraries in the current folder.

Fix python build
